CREATE TABLE USERS
(
 id VARCHAR(11) NOT NULL ,
 name VARCHAR(100) DEFAULT NULL,
 address VARCHAR(100) DEFAULT NULL,
 email VARCHAR(100) DEFAULT NULL,
 checked BOOLEAN DEFAULT FALSE,
 PRIMARY KEY (id)
);